name: Validate Markdown

on:
  push:
    paths:
    - 'README.md'

jobs:
  mdl:
    name: Markdown Lint CLI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: README.md
          config_file: ".markdownlint.json"
